name: MorphSeg

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip

  - pip:
    - spacy==3.8.8
    - torch==2.9.0
    - pandas==2.3.3
    - tqdm==4.67.1
    - numpy==2.3.4
    - rich==14.2.0
    - editdistance==0.8.1